### ISSUE TITLE
Missing web3 parameter in README.md in getExchange function

### ISSUE THREAD

**Issue by robertmagier** [HardlyDifficult/hardlydifficult-test-helpers#58]
This code in Uniswap example in README.md
```
const exchange = protocols.uniswap.getExchange(
  tx.logs[0].args.exchange
);
```
 should be changed to (add **web3** parameter): 
```
const exchange = protocols.uniswap.getExchange(web3,
  tx.logs[0].args.exchange
);
```

In other case it will fail with below error message:
```
     Error: Invalid provider passed to setProvider(); provider is undefined
      at Function.setProvider (node_modules/truffle-contract/lib/contract/constructorMethods.js:9:13)
      at Object.getExchange (node_modules/hardlydifficult-test-helpers/src/protocols/uniswap.js:35:30)

```

This is because getExchange function is defined as:
`getExchange: async (web3, exchangeAddress)`

**Comment by NickCuso** [comment]
Ah sorry for this, will update the readme now.  Thanks for letting me know.
